name: "Semantic Pull Request"

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
permissions:
  contents: read
jobs:
  main:
    name: Validate PR and Commits
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@0184f5a228ee06430bb9e67d65f73a1a6767496a # v6.2.0
        with:
          configFile: .github/commitlint.config.cjs
      - name: Install Dependencies
        run: npm install @commitlint/config-conventional@18.5
      - uses: JulienKode/pull-request-name-linter-action@8c05fb989d9f156ce61e33754f9802c9d3cffa58 # v0.5.0
        with:
          configuration-path: ./.github/commitlint.config.cjs
